### ISSUE TITLE
Error: Onkyo does not support ZVL command

### ISSUE THREAD

**Issue by Albatros2409** [nitaybz/homebridge-onkyo-pioneer#2]
Thanks very much for the excelent plugin. Works great with my Onkyo TX-NR5010. Have got two devices, zone 1 and zone2 with volume and input control!! 

It is working but the log shows one error message. Not sure what it means or it does something.

[1/8/2021, 11:47:36 AM] [OnkyoPioneer] Error: Onkyo does not support ZVL command
[1/8/2021, 11:47:36 AM] [OnkyoPioneer] ERROR OCCURRED: RX: unknown event: Error: Onkyo does not support ZVL command
[1/8/2021, 11:47:40 AM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1ZVLQSTN
  at afterTimeout (/usr/local/lib/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
  at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
  at listOnTimeout (internal/timers.js:554:17)
  at processTimers (internal/timers.js:497:7)
[1/8/2021, 11:47:40 AM] [OnkyoPioneer] Could NOT get state from "Onkyo Zone 2" : Timeout when sending: !1ZVLQSTN
[1/8/2021, 11:47:40 AM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1ZVLQSTN
[1/8/2021, 11:47:40 AM] [OnkyoPioneer] Onkyo Zone 2 - found cached state in storage
[1/8/2021, 11:48:05 AM] [OnkyoPioneer] Onkyo - Getting State
[1/8/2021, 11:48:05 AM] [OnkyoPioneer] Onkyo Zone 2 - Getting State
[1/8/2021, 11:48:06 AM] [OnkyoPioneer] Onkyo - Got New State: {"power":0,"volume":53,"mute":false,"source":3}
[1/8/2021, 11:48:06 AM] [OnkyoPioneer] Error: Onkyo does not support ZVL command
[1/8/2021, 11:48:06 AM] [OnkyoPioneer] ERROR OCCURRED: RX: unknown event: Error: Onkyo does not support ZVL command

**Comment by nitaybz** [comment]
it's a warning actually and can be ignored.

**Comment by Albatros2409** [comment]
Oke thanks very much it is an excellent plugin.

One issue I have is that the zone 2 in home app shows On when it is off. This is what happens: turn on zone 2 works fine, home app show on. Truning Zone 2 off does switch zone 2 off. The home app shows zone 2 for one second of but than it shows on but actualy zone 2 is off.

Do you know what the issue could be.

________________________________
Van: Nitay Ben-Zvi <notifications@github.com>
Verzonden: dinsdag 9 februari 2021 09:01
Aan: nitaybz/homebridge-onkyo-pioneer <homebridge-onkyo-pioneer@noreply.github.com>
CC: Albatros2409 <tacoroest@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [nitaybz/homebridge-onkyo-pioneer] Error: Onkyo does not support ZVL command (#2)


it's a warning actually and can be ignored.

**Comment by nitaybz** [comment]
open a new issue, enable debug logs from the plugin settings and attach the logs so I can understand why it shows as ON

**Comment by nitaybz** [comment]
Latest version v0.0.18 should fix the issue

**Comment by iondarie** [comment]
i am on v0.0.18 and i have the same issue:

```
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Onkyo TX-NR636 constructed
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Scanning for "192.168.0.14"
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] created listen server
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] server listening 0.0.0.0:60128
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21xECNQSTN%0D
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00%21pECNQSTN%0D
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Write ok
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Write ok
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] RX: ISCP%00%00%00%10%00%00%00%26%01%00%00%00%211ECNTX-NR636/60128/XX/0009B0D40E01%19%0D%0A%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] RX message: ECNTX-NR636/60128/XX/0009B0D40E01
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Parse DISCOVER msg: ECNTX-NR636/60128/XX/0009B0D40E01%19
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] New onkyo: {"address":"192.168.0.14","port":60128,"info":{"category":"C","modelName":"TX-NR636","ISCPport":"60128","area":"European or Asian model","identifier":"0009B0D40E01"}}
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] detected new: TX-NR636#0 192.168.0.14:60128
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Found AVR "TX-NR636" at 192.168.0.14:
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] {
  name: 'TX-NR636#0',
  address: '192.168.0.14',
  port: 60128,
  info: {
    category: 'C',
    modelName: 'TX-NR636',
    ISCPport: '60128',
    area: 'European or Asian model',
    identifier: '0009B0D40E01'
  }
}
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] socket closed
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Full Device Config: {"name":"TX-NR636#0","address":"192.168.0.14","port":60128,"info":{"category":"C","modelName":"TX-NR636","ISCPport":"60128","area":"European or Asian model","identifier":"0009B0D40E01"},"id":"0009B0D40E01","main":{"name":"TX-NR636","inputs":[{"identifier":0,"name":"NET","key":"NET","hidden":0},{"identifier":1,"name":"VIDEO1","key":"VIDEO1","hidden":0},{"identifier":2,"name":"VIDEO2","key":"VIDEO2","hidden":0},{"identifier":3,"name":"CBL/SAT","key":"CBL/SAT","hidden":0},{"identifier":4,"name":"GAME","key":"GAME","hidden":0},{"identifier":5,"name":"AUX","key":"AUX","hidden":0},{"identifier":6,"name":"VIDEO5","key":"VIDEO5","hidden":0},{"identifier":7,"name":"PC","key":"PC","hidden":0},{"identifier":8,"name":"VIDEO6","key":"VIDEO6","hidden":0},{"identifier":9,"name":"VIDEO7","key":"VIDEO7","hidden":0},{"identifier":10,"name":"BD/DVD","key":"BD/DVD","hidden":0},{"identifier":11,"name":"STREAM","key":"STREAM","hidden":0},{"identifier":12,"name":"TV","key":"TV","hidden":0},{"identifier":13,"name":"TAPE1","key":"TAPE1","hidden":0},{"identifier":14,"name":"TAPE2","key":"TAPE2","hidden":0},{"identifier":15,"name":"PHONO","key":"PHONO","hidden":0},{"identifier":16,"name":"CD","key":"CD","hidden":0},{"identifier":17,"name":"FM","key":"FM","hidden":0},{"identifier":18,"name":"AM","key":"AM","hidden":0},{"identifier":19,"name":"TUNER","key":"TUNER","hidden":0},{"identifier":20,"name":"MUSICSERVER","key":"MUSICSERVER","hidden":0},{"identifier":21,"name":"INTERNETRADIO","key":"INTERNETRADIO","hidden":0},{"identifier":22,"name":"USB","key":"USB","hidden":0},{"identifier":23,"name":"USB_REAR","key":"USB_REAR","hidden":0},{"identifier":24,"name":"USB_C","key":"USB_C","hidden":0},{"identifier":25,"name":"AIRPLAY","key":"AIRPLAY","hidden":0},{"identifier":26,"name":"BT","key":"BT","hidden":0},{"identifier":27,"name":"MULTICH","key":"MULTICH","hidden":0},{"identifier":28,"name":"XM","key":"XM","hidden":0},{"identifier":29,"name":"SIRIUS","key":"SIRIUS","hidden":0}],"maxVolume":100,"volume":{"name":"TX-NR636 Volume"}},"zone2":{"active":true,"name":"","inputs":[{"identifier":0,"name":"NET","key":"NET","hidden":0},{"identifier":1,"name":"CBL/SAT","key":"CBL/SAT","hidden":0},{"identifier":2,"name":"GAME","key":"GAME","hidden":0},{"identifier":3,"name":"AUX","key":"AUX","hidden":0},{"identifier":4,"name":"BD/DVD","key":"BD/DVD","hidden":0},{"identifier":5,"name":"STRM_BOX","key":"STRM_BOX","hidden":0},{"identifier":6,"name":"TV","key":"TV","hidden":0},{"identifier":7,"name":"PHONO","key":"PHONO","hidden":0},{"identifier":8,"name":"CD","key":"CD","hidden":0},{"identifier":9,"name":"FM","key":"FM","hidden":0},{"identifier":10,"name":"AM","key":"AM","hidden":0},{"identifier":11,"name":"TUNER","key":"TUNER","hidden":0},{"identifier":12,"name":"USB_FRONT","key":"USB_FRONT","hidden":0},{"identifier":13,"name":"USB_REAR","key":"USB_REAR","hidden":0},{"identifier":14,"name":"BT","key":"BT","hidden":0},{"identifier":15,"name":"HDMI_5","key":"HDMI_5","hidden":0}],"volume":{"name":"TX-NR636 Zone2 Volume"}},"zone3":{"name":"","inputs":[{"identifier":0,"name":"NET","key":"NET","hidden":0},{"identifier":1,"name":"CBL/SAT","key":"CBL/SAT","hidden":0},{"identifier":2,"name":"GAME","key":"GAME","hidden":0},{"identifier":3,"name":"AUX","key":"AUX","hidden":0},{"identifier":4,"name":"BD/DVD","key":"BD/DVD","hidden":0},{"identifier":5,"name":"STRM_BOX","key":"STRM_BOX","hidden":0},{"identifier":6,"name":"TV","key":"TV","hidden":0},{"identifier":7,"name":"PHONO","key":"PHONO","hidden":0},{"identifier":8,"name":"CD","key":"CD","hidden":0},{"identifier":9,"name":"FM","key":"FM","hidden":0},{"identifier":10,"name":"AM","key":"AM","hidden":0},{"identifier":11,"name":"TUNER","key":"TUNER","hidden":0},{"identifier":12,"name":"USB_FRONT","key":"USB_FRONT","hidden":0},{"identifier":13,"name":"USB_REAR","key":"USB_REAR","hidden":0},{"identifier":14,"name":"BT","key":"BT","hidden":0},{"identifier":15,"name":"HDMI_5","key":"HDMI_5","hidden":0}],"volume":{"name":""}}}
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Creating New AUDIO RECEIVER Accessory: "TX-NR636"
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] TX-NR636 - Getting State
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Adding Zone 2 for TX-NR636
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] Creating New AUDIO RECEIVER Accessory: "TX-NR636 Zone2"
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] TX-NR636 Zone2 - Getting State
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] wait for event: ZPW
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] TX-msg: !1ZPWQSTN
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00!1ZPWQSTN%0D
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] wait for event: PWR
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] TX-msg: !1PWRQSTN
[10/18/2021, 8:38:34 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00!1PWRQSTN%0D

[10/18/2021, 8:38:38 PM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1ZPWQSTN
    at afterTimeout (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1ZPWQSTN
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] Trying to reconnect...
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] Could NOT get state from "TX-NR636 Zone2" : Timeout when sending: !1ZPWQSTN
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - found cached state in storage
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: NET
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: CBL/SAT
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: GAME
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: AUX
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: BD/DVD
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: STRM_BOX
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: TV
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: PHONO
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: CD
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: FM
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: AM
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: TUNER
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: USB_FRONT
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: USB_REAR
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: BT
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Adding INPUT: HDMI_5
Preparing Advertiser for 'TX-NR636 Zone2 5ADC' using ciao backend!
Starting to advertise 'TX-NR636 Zone2 5ADC' using ciao backend!
[10/18/2021, 8:38:38 PM] TX-NR636 Zone2 5ADC is running on port 45013.
[10/18/2021, 8:38:38 PM] Please add [TX-NR636 Zone2 5ADC] manually in Home app. Setup Code: 280-22-013
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1PWRQSTN
    at afterTimeout (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1PWRQSTN
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] Trying to reconnect...
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] Could NOT get state from "TX-NR636" : Timeout when sending: !1PWRQSTN
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - found cached state in storage
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: NET
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: VIDEO1
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: VIDEO2
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: CBL/SAT
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: GAME
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: AUX
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: VIDEO5
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: PC
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: VIDEO6
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: VIDEO7
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: BD/DVD
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: STREAM
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: TV
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: TAPE1
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: TAPE2
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: PHONO
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: CD
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: FM
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: AM
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: TUNER
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: MUSICSERVER
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: INTERNETRADIO
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: USB
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: USB_REAR
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: USB_C
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: AIRPLAY
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: BT
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: MULTICH
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: XM
[10/18/2021, 8:38:38 PM] [OnkyoPioneer] TX-NR636 - Adding INPUT: SIRIUS
Preparing Advertiser for 'TX-NR636 DE1C' using ciao backend!
Starting to advertise 'TX-NR636 DE1C' using ciao backend!
[10/18/2021, 8:38:38 PM] TX-NR636 DE1C is running on port 33657.
[10/18/2021, 8:38:38 PM] Please add [TX-NR636 DE1C] manually in Home app. Setup Code: 280-22-013

[10/18/2021, 8:39:08 PM] [OnkyoPioneer] TX-NR636 Zone2 - Getting State
[10/18/2021, 8:39:08 PM] [OnkyoPioneer] wait for event: ZPW
[10/18/2021, 8:39:08 PM] [OnkyoPioneer] TX-msg: !1ZPWQSTN
[10/18/2021, 8:39:08 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00!1ZPWQSTN%0D
[10/18/2021, 8:39:08 PM] [OnkyoPioneer] TX-NR636 - Getting State
[10/18/2021, 8:39:08 PM] [OnkyoPioneer] wait for event: PWR
[10/18/2021, 8:39:08 PM] [OnkyoPioneer] TX-msg: !1PWRQSTN
[10/18/2021, 8:39:08 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00!1PWRQSTN%0D
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1ZPWQSTN
    at afterTimeout (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] Trying to reconnect...
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1ZPWQSTN
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] Could NOT get state from "TX-NR636 Zone2" : Timeout when sending: !1ZPWQSTN
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] TX-NR636 Zone2 - found cached state in storage
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1PWRQSTN
    at afterTimeout (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1PWRQSTN
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] Trying to reconnect...
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] Could NOT get state from "TX-NR636" : Timeout when sending: !1PWRQSTN
[10/18/2021, 8:39:12 PM] [OnkyoPioneer] TX-NR636 - found cached state in storage

[10/18/2021, 8:39:38 PM] [OnkyoPioneer] TX-NR636 Zone2 - Getting State
[10/18/2021, 8:39:38 PM] [OnkyoPioneer] wait for event: ZPW
[10/18/2021, 8:39:38 PM] [OnkyoPioneer] TX-msg: !1ZPWQSTN
[10/18/2021, 8:39:38 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00!1ZPWQSTN%0D
[10/18/2021, 8:39:38 PM] [OnkyoPioneer] TX-NR636 - Getting State
[10/18/2021, 8:39:38 PM] [OnkyoPioneer] wait for event: PWR
[10/18/2021, 8:39:38 PM] [OnkyoPioneer] TX-msg: !1PWRQSTN
[10/18/2021, 8:39:38 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00!1PWRQSTN%0D
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1ZPWQSTN
    at afterTimeout (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] Trying to reconnect...
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1ZPWQSTN
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] Could NOT get state from "TX-NR636 Zone2" : Timeout when sending: !1ZPWQSTN
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] TX-NR636 Zone2 - found cached state in storage
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1PWRQSTN
    at afterTimeout (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] Trying to reconnect...
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1PWRQSTN
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] Could NOT get state from "TX-NR636" : Timeout when sending: !1PWRQSTN
[10/18/2021, 8:39:42 PM] [OnkyoPioneer] TX-NR636 - found cached state in storage
[10/18/2021, 8:40:04 PM] [DS720+] updating temperature to 39 °C
[10/18/2021, 8:40:08 PM] [OnkyoPioneer] TX-NR636 Zone2 - Getting State
[10/18/2021, 8:40:08 PM] [OnkyoPioneer] wait for event: ZPW
[10/18/2021, 8:40:08 PM] [OnkyoPioneer] TX-msg: !1ZPWQSTN
[10/18/2021, 8:40:08 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00!1ZPWQSTN%0D
[10/18/2021, 8:40:08 PM] [OnkyoPioneer] TX-NR636 - Getting State
[10/18/2021, 8:40:08 PM] [OnkyoPioneer] wait for event: PWR
[10/18/2021, 8:40:08 PM] [OnkyoPioneer] TX-msg: !1PWRQSTN
[10/18/2021, 8:40:08 PM] [OnkyoPioneer] TX: ISCP%00%00%00%10%00%00%00%0A%01%00%00%00!1PWRQSTN%0D
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1ZPWQSTN
    at afterTimeout (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] Trying to reconnect...
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1ZPWQSTN
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] Could NOT get state from "TX-NR636 Zone2" : Timeout when sending: !1ZPWQSTN
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] TX-NR636 Zone2 - found cached state in storage
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] SubError [TimeoutError]: Timeout when sending: !1PWRQSTN
    at afterTimeout (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:49:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/homebridge/node_modules/homebridge-onkyo-pioneer/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] ERROR OCCURRED: Timeout when sending: !1PWRQSTN
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] Trying to reconnect...
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] Could NOT get state from "TX-NR636" : Timeout when sending: !1PWRQSTN
[10/18/2021, 8:40:12 PM] [OnkyoPioneer] TX-NR636 - found cached state in storage
```

**Comment by nitaybz** [comment]
Should be addressed in v0.1.0 (just published). Per-field state reads, log-once for unsupported commands, and HB v2 compat are all in. Please update and let me know if anything still misbehaves.

Sorry for the long delay on this.
